<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>scopeName</key>
    <string>source.c.linker</string>
    <key>fileTypes</key>
    <array>
      <string>ld</string>
    </array>
    <key>foldingStartMarker</key>
    <string>{</string>
    <key>foldingStopMarker</key>
    <string>}</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>name</key>
        <string>support.function.ld</string>
        <key>match</key>
        <string>\b(?:S(?:E(?:ARCH_DIR|CTIONS)|IZEOF(?:_HEADERS)?|TARTUP)|IN(?:HIBIT_COMMON_ALLOCATION|CLUDE|PUT)|D(?:ATA_SEGMENT_(?:ALIGN|END)|EFINED)|O(?:UTPUT(?:_(?:FORMAT|ARCH))?|RIGIN)|C(?:REATE_OBJECT_SYMBOL|ONSTRUCTOR)S|(?:FORCE_COMMON_ALLOCATIO|HIDDE)N|E(?:X(?:CLUDE_FILE|TERN)|NTRY)|P(?:ROVIDE(?:_HIDDEN)?|HDRS)|A(?:BSOLUTE|SSERT|LIGN|DDR)|N(?:OCROSSREFS|EXT)|L(?:OADADDR|ENGTH)|M(?:EMORY|AX|IN)|sizeof_headers|l(?:en)?|o(?:rg)?|TARGET|BLOCK|GROUP)\b</string>
      </dict>
      <dict>
        <key>match</key>
        <string>(BYTE|SHORT|LONG|S?QUAD)\s*\(([^\)]*)\)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.ld</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.ld</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>match</key>
        <string>((?=.*[^A-Z])[^\s\(;\:\{\}]*)\s*\(([^\),"]*)\)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>variable.other.source.ld</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.other.section.ld</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>match</key>
        <string>([^\s\(;\:\{\}]*)(\s+[^\(\s\:\}]+|\s*\([^\)]*\))?\s*\:\s*(AT\s*\([^\)]*\))?</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>constant.other.section.ld</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.address.ld</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>keyword.other.at.ld</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>match</key>
        <string>\}\s*\&gt;\s*([^\s\&gt;\:]*)\s*(AT\s*)?(?:\&gt;\s*)?([^\=\&gt;]*)?\=\s*([^\s;\}]*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.memory.ld</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.other.at.ld</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.memory.ld</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.address.ld</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>match</key>
        <string>([^\s\(;\{\}]*)\s*\(\s*([RrWwXx\!]{,4})\s*\)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.memory.ld</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>support.constant.permissions.ld</string>
          </dict>
        </dict>
      </dict>
    </array>
  </dict>
</plist>
